### ISSUE TITLE
Q: What is syntax for specify attributes for CreateHostReqest ?

### ISSUE THREAD

**Issue by tjyang** [lebe-dev/zabbix-api-rs#11]
@lebe-dev 
Would you please provide an example of passing interface attributes using vec![] ?
- [zabbix api create.host ](https://www.zabbix.com/documentation/current/en/manual/api/reference/host/create) json example
![image](https://github.com/lebe-dev/zabbix-api-rs/assets/378638/d346f473-34bb-4b12-8f0e-a4c3517f8358)
- CreateHostRequest rust code snippet 
```
           let request = CreateHostRequest {
                host: host_name,
                groups: vec![host_group],
                interfaces: vec![
                    "type",
                    1,
                    "main",
                    1,
                    "useip",
                    1,
                    "ip",
                    "192.168.3.1",
                    "dns",
                    "",
                    "port",
                    "10050",
                ],
                tags: vec![],
                templates: vec![],
                macros: vec![],
                inventory_mode: 0,
                inventory: Default::default(),
            };

```

**Comment by lebe-dev** [comment]
Zabbix API is huge and dynamic (hello from php world), so, I can't implement all possible fields for request struct based on Zabbix API object :) I've implemented just what i needed. But api client methods allows you to implement any structure you want.

Just don't use current CreateHostRequest and implement your own request struct. The only one requirement - your struct should have `Serialize`:

```rust
#[derive(Serialize)]
struct CustomCreateHostRequest {
  // any fields you want
}
```

**Comment by tjyang** [comment]
Thanks for CustomCreateHostRequest hint.
Would you please provide and complete rust code example on specifying  interfaces parameters ?

- example code using  CustomCreateHostRequest
```
           let request = CustomCreateHostRequest {
                host: host_name,
                groups: vec![host_group],
                interfaces: vec![
                    "type",
                    1,
                    "main",
                    1,
                    "useip",
                    1,
                    "ip",
                    "192.168.3.1",
                    "dns",
                    "",
                    "port",
                    "10050",
                ],
                tags: vec![],
                templates: vec![],
                macros: vec![],
                inventory_mode: 0,
                inventory: Default::default(),
            };

``

**Comment by lebe-dev** [comment]
Based on example `interfaces` field should have type `Vec<String>`:

```rust
#[derive(Serialize)
struct CreateHostRequest {
  ...
  pub interfaces: Vec<String>
  ...
}
```

**Comment by lebe-dev** [comment]
I would implement struct ZabbixInterface with fields you need - https://www.zabbix.com/documentation/6.0/en/manual/api/reference/hostinterface/object

Then implement something like this:

```rust
#[derive(Serialize)]
struct CreateHostRequest {
  ...
  pub interfaces: Vec<ZabbixInterface>
  ...
}
```

**Comment by tjyang** [comment]
Sorry Rust beginner here.  I failed to understand. This will be a good beginner home work I guest ;)
I have to study on how to use serialize syntax and example.

**Comment by tjyang** [comment]
I am closing this ticket for. I decided to use different approach to do CRUD opts with zabbix API. 
Thanks.
