### ISSUE TITLE
RFE: Support more Host objects/parameters like psk related objects

### ISSUE THREAD

**Issue by tjyang** [lebe-dev/zabbix-api-rs#12]
@lebe-dev 
I am hoping to create the host with PSK enabled on zabbix server side.
- Existing host objects doesn't support PSK related objects.
![image](https://github.com/lebe-dev/zabbix-api-rs/assets/378638/830edfa0-bfce-454d-a829-33f6c412c431)

```
  pub host: String,
    pub groups: Vec<ZabbixHostGroup, Global>,
    pub interfaces: Vec<ZabbixHostInterface, Global>,
    pub tags: Vec<ZabbixHostTag, Global>,
    pub templates: Vec<ZabbixTemplate, Global>,
    pub macros: Vec<ZabbixHostMacro, Global>,
    pub inventory_mode: u8,
    pub inventory: HashMap<String, String, RandomState>,
```

- [psk related objcts](https://www.zabbix.com/documentation/current/en/manual/api/reference/host/object#host)
![image](https://github.com/lebe-dev/zabbix-api-rs/assets/378638/f37f2d7b-de17-4928-8a1f-07ebce040028)

**Comment by lebe-dev** [comment]
Answered in another issue.

Details here: https://github.com/lebe-dev/zabbix-api-rs/issues/11#issuecomment-1919453804
