### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tjyang** [lebe-dev/zabbix-api-rs#14]
Hi @lebe-dev 
I don't know the real difference between MIT and GNU license term.

- WHAT: Since [zabbix itself is using GNU](https://github.com/zabbix/zabbix/blob/master/COPYING). Would you consider re-license your work into  GNU one 

- WHY: Better chance in the long run to compete with existing Zabbix API frameworks like[ zabbix-cli, ](https://github.com/unioslo/zabbix-cli) and [official  python api .](https://github.com/zabbix/python-zabbix-utils).. etc.

**Comment by lebe-dev** [comment]
Hi. 

MIT License allows you to use code for any kind of software (open source and proprietary).

Restrictions and Requirements:

- MIT License: It is a permissive license that is short and to the point. It allows for almost unrestricted freedom to use, copy, modify, and distribute the software, with minimal requirements. The MIT License is designed to promote software freedom by allowing proprietary and open source software to coexist and benefit from MIT-licensed code.

- MIT License: Requires only that the original license and copyright notice be included with any substantial portions of the software. It does not require derivative works to be open source.

- GNU General Public License (GPL): Requires that any derivative work also be licensed under the GPL. This means that any software that includes GPL-licensed code must also be open source and distributed under the GPL, which can restrict the use of GPL-licensed code in proprietary software.

**Comment by tjyang** [comment]
Thanks for taking time to list out the license diff.
Sorry, I re-checked zabbix official [supported python api is using MIT license.](https://github.com/zabbix/python-zabbix-utils/blob/main/LICENSE). So whether MIT or GNU or not. this framework can become official supported zabbix client api using Rust ;)
